### ISSUE TITLE
onclick 짜다가 고민중인거

### ISSUE THREAD

**Issue by wishJinit** [FontChecker/FontChecker-Android#6]
1번이랑 2번중에 어떻게 짜는게 좋을까 고민중인데 어떻게 생각하시나요..?

1.
when (v) {
            binding?.button1 -> 어쩌구
            binding?.button2 -> 저쩌구
}

2.
with (binding) {
     when (v) {
            button1 -> 어쩌구
            button2 -> 저쩌구
     }
}

**Comment by CaptainWonJong** [comment]
코드품질 고민은 스스로 고민하고 PR 요청 해주세요.
